name: build-action
on:
    push

jobs:
    build:
        runs-on: macos-latest
        steps:
        #Check current repository
        - name: Checkout
          uses: actions/checkout@v3
          
        #Initial Setup Gradle, can be used by a subseqeuent Gradle invocation benefitting of cache
        - name: Setup Gradle
          uses: gradle/gradle-build-action@v2
          
        #Execute assemble
        - name: Execute Gradle assemble
          id: assemble
          run: ./gradlew assemble
          
        #Runs if all previous steps are succedded
        - if: ${{ success() }}
          uses: Sibz/github-status-action@v1
          with:
            authToken: ${{secrets.GITHUB_TOKEN}}    #default token
            context: 'Build run'
            description: 'Build passed'
            state: 'success'
            sha: ${{github.event.pull_request.head.sha || github.sha}}
        #Runs if assemble step fails
        - if: ${{failure() && steps.assemble.conclusion == 'failure'}}
          uses: Sibz/github-status-action@v1
          with:
            authToken: ${{secrets.GITHUB_TOKEN}}
            context: 'Build run'
            description: 'Build failed'
            state: 'failure'
            sha: ${{github.event.pull_request.head.sha || github.sha}}
 
          
          
