# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_run:
    workflows: [build-action]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v3
      - if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: echo 'The triggering workflow passed'
