name: build-action
on:
    status

jobs:
    build:
        runs-on: macos-latest
        if: >- 
          github.event.state == 'success'
        steps:
        #Check current repository
        - name: Checkout
          uses: actions/checkout@v3
        #Initial Setup Gradle, can be used by a subseqeuent Gradle invocation benefitting of cache
        - name: Setup Gradle
          uses: gradle/gradle-build-action@v2
          
        #Execute assemble
        - name: Execute Gradle assemble
          run: ./gradlew assemble 
          if: ${{ success() }}
