name: build-action
on:
    push:

jobs:
    build:
        runs-on: macos-latest
        outputs:
            build-output: ${{ steps.assemble.outputs.test }}
        steps:
        #Check current repository
        - name: Checkout
          uses: actions/checkout@v3
        #Initial Setup Gradle, can be used by a subseqeuent Gradle invocation benefitting of cache
        - name: Setup Gradle
          uses: gradle/gradle-build-action@v2
          
        #Execute assemble
        - id: assemble 
        - name: Execute Gradle assemble
          run: ./gradlew assemble; echo "::set-output name=test::$?"
          
        
    
                 
        
      
  
    


