name: kdoc-action

on:
  release:
    types:
      - published

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      #Setup Environment Variables
      #- uses: FranzDiebold/github-env-vars-action@v2

      - name: Generate Html documentation
        run: ./gradlew dokkaHtml

      - name: Setup branch gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./hara-ddiclient-api/build/dokka/html
          keep_files: true
          destination_dir: ${{ github.ref_name }}

